name: Rust

on: push

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout solutions
        uses: actions/checkout@v3
        with:
          path: aoc_solutions/

      - name: Checkout private inputs
        uses: actions/checkout@v3
        with:
          repository: drflowerkick/aoc_input
          ref: main
          token: ${{ secrets.AOC_INPUT_TOKEN }}
          path: aoc_input/
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        working-directory: aoc_solutions/
        run: cargo test --workspace --all-features --release

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout solutions
        uses: actions/checkout@v3
        with:
          path: aoc_solutions/

      - name: Checkout private inputs
        uses: actions/checkout@v3
        with:
          repository: drflowerkick/aoc_input
          ref: main
          token: ${{ secrets.AOC_INPUT_TOKEN }}
          path: aoc_input/
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Enforce formatting
        working-directory: aoc_solutions/
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout solutions
        uses: actions/checkout@v3
        with:
          path: aoc_solutions/

      - name: Checkout private inputs
        uses: actions/checkout@v3
        with:
          repository: drflowerkick/aoc_input
          ref: main
          token: ${{ secrets.AOC_INPUT_TOKEN }}
          path: aoc_input/
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Linting
        working-directory: aoc_solutions/
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
